inputs_def:
  - handle: zip_path
    description: "%path-to-existing-zip-file%"
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        excludeAll: true
        filters:
          - name: ZIP
            extensions:
              - zip
    nullable: false

  - handle: files_to_add
    description: "%files-or-folders-to-add-to-zip%"
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
    nullable: false

  - group: Optional Settings
    collapsed: true

  - handle: archive_path_prefix
    description: "%optional-prefix-for-files-in-archive%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: password
    description: "%password-if-zip-is-encrypted-optional%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: overwrite_existing
    description: "%overwrite-files-if-they-already-exist-in-zip%"
    json_schema:
      type: boolean
    value: false
    nullable: false

outputs_def:
  - handle: zip_path
    description: "Path to modified ZIP file"
    json_schema:
      type: string

  - handle: added_files_count
    description: "Number of files successfully added"
    json_schema:
      type: number

  - handle: new_size
    description: "New size of ZIP file in bytes"
    json_schema:
      type: number

  - handle: files_added
    description: "List of files that were added"
    json_schema:
      type: array
      items:
        type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%add-files-to-zip-archive%"
icon: ":carbon:add-alt:"
description: "%add-new-files-or-folders-to-an-existing-zip-archive%"
